use of a single channel of structured data + waitgroup
bryanpedini/go-ping-monitor pull request #1
Opened 2021-02-22 16:53 UTC by ilmanzo

2021-02-22 23:13 UTC, bryanpedini commented on .gitignore
> +go-ping-monitor
😅 usando `go run .` non l'ho mai inserito...

2021-02-22 23:21 UTC, bryanpedini commented on main.go
> +		fmt.Printf("ping %s -> rtt %s ms\n", res.host, res.result)
Any reason why "rtt"? I would like to display the average ping.

2021-02-22 23:25 UTC, bryanpedini requested changes
Need feedback.

2021-02-22 23:25 UTC, bryanpedini commented on .gitignore
> +go-ping-monitor
Always using `go run .` I never got it... 😅

2021-02-22 23:25 UTC, bryanpedini commented on main.go
> +		fmt.Printf("ping %s -> rtt %s ms\n", res.host, res.result)
Any reason why "rtt"? I would like to display the average ping.

2021-02-22 23:26 UTC, bryanpedini commented on .gitignore
> +go-ping-monitor
Well, actually, **this** does not require any change.

2021-02-23 14:30 UTC, ilmanzo commented on .gitignore
> +go-ping-monitor
If someone runs "go build" it will create a binary with that name, so I added the binary in .gitignore

2021-02-23 14:31 UTC, ilmanzo commented on main.go
> +		fmt.Printf("ping %s -> rtt %s ms\n", res.host, res.result)
no particular reason, you can put whatever message you prefer.

2021-02-23 14:32 UTC, bryanpedini commented on .gitignore
> +go-ping-monitor
Yup, I know, I just didn't think to add this since I usually don't `go build` but `go run .` 😅

2021-02-23 14:32 UTC, bryanpedini commented on main.go
> +		fmt.Printf("ping %s -> rtt %s ms\n", res.host, res.result)
Got it!

2021-02-23 14:36 UTC, bryanpedini approved these changes

2021-02-23 14:37 UTC, merged